.TH NN-CONFIG 1 "2026" "nn 0.1.0" "NN Manual"
.SH NAME
nn-config \- git-like configuration
.SH SYNOPSIS
.B nn config [options] [key] [value]
.SH DESCRIPTION
Read or write user configuration keys such as color.ui.
.SH OPTIONS
.TP
.B \-\-list
List all.
.TP
.B \-\-get KEY
Get one.
.TP
.B \-\-unset KEY
Remove one.
.SH EXIT STATUS
0 success.
.SH EXAMPLES
.nf
nn config --list
.fi
.SH SEE ALSO
nn(1)
