.TH NN-VERSION 1 "2026" "nn 0.1.0" "NN Manual"
.SH NAME
nn-version \- show version
.SH SYNOPSIS
.B nn version [--build-options]
.SH DESCRIPTION
Print the nn version string.
.SH OPTIONS
.TP
.B \-\-build\-options
Compiler, commit, enabled modules.
.SH EXIT STATUS
0 success.
.SH EXAMPLES
.nf
nn version --build-options
.fi
.SH SEE ALSO
nn-doctor(1)
